update backup script to use multiple tape drivers

diff --git a/bin/.bin/server/dir2tape b/bin/.bin/server/dir2tape
--- a/bin/.bin/server/dir2tape
+++ b/bin/.bin/server/dir2tape
@@ -2,38 +2,45 @@
 MTX="/usr/local/bin/mtx"
 MT="/usr/bin/mt"
 SG="/usr/bin/sg_read_attr"
-TAPEDRIVEMODEL="HH6"
-TAPE=$(lsscsi | grep $TAPEDRIVEMODEL | awk '{print $6}')
-TAPE=$(echo "/dev/nst${TAPE: -1:1}")
-BS=1024
-TAPELIBRARYMODEL="mediumx"
-TAPELIBRARY=$(lsscsi -g | grep $TAPELIBRARYMODEL | awk '{print $7}')
-TAPEDRIVE=${TAPE: -1:1}
+RE='^[0-9]+$'
+DRIVE=${DRIVE:-0}
+[[ $DRIVE =~ $RE ]] || exit 1
+if [[ "$DRIVE" -eq 0 ]]; then
+    TAPE=/dev/tape/by-path/pci-0000:0b:00.1-fc-0x2002000e11150604-lun-0-nst
+elif [[ "$DRIVE" -eq 1 ]]; then
+    TAPE=/dev/tape/by-path/pci-0000:85:00.0-sas-phy3-lun-0-nst
+else
+    echo "Drive not found"
+    exit 1
+fi
+TAPEREWIND_TIMEOUT=300
+TAPEREADY_TIMEOUT=3
+TAPELIBRARY=/dev/tape/by-path/pci-0000:0b:00.1-fc-0x2002000e11150604-lun-1-changer
+BS=${BS:-512}
+[[ $BS =~ $RE ]] || exit 1
+FILES_ONTAPE=0
 
 function usage {
     echo "$(basename $0) [options] directory slot [nslots]"
     echo "options:"
+    echo "[-f] Full Backup (will erase tape first)"
     echo "[-s] Statistics only"
-    echo "[-t <Tape dev>] default $TAPE"
-    echo "[-b <n blocksize>] \"n*512bytes\" default $((BS * 512 / 1024))kb"
+    echo "[-v Verbose]"
     exit 1
 }
 
-while getopts "b:t:sf" o; do
+while getopts "fsv" o; do
     case "${o}" in
-    s) STATS_ONLY=TRUE ;;
-    t)
-        TAPE=$OPTARG
-        TAPEDRIVE=${TAPE: -1:1}
-        ;;
-    # b) BS=$OPTARG ;;
     f) FULL=TRUE ;;
+    s) STATS_ONLY=TRUE ;;
+    v) VERBOSE=TRUE ;;
     *) usage ;;
     esac
 done
 shift $((OPTIND - 1))
 
 function findEOM {
+    [[ -n $FULL ]] && eraseTape
     echo "Finding EOM..."
     local count=3
     while true; do
@@ -51,27 +58,27 @@ function findEOM {
 }
 
 function unloadTape {
-    local driveStatus=$($MTX -f ${TAPELIBRARY} status | grep "Data Transfer Element ${TAPEDRIVE}:")
+    local driveStatus=$($MTX -f ${TAPELIBRARY} status | grep "Data Transfer Element ${DRIVE}:")
     local driveLoaded=$(echo $driveStatus | awk -F ':' '{print $2}')
     [[ ${driveLoaded} == "Empty" ]] && return 0
     local storageSlot=$(echo $driveStatus | awk '{print $7}')
-    $MTX -f $TAPELIBRARY unload $storageSlot $TAPEDRIVE
-}
-
-function loadTape {
-    unloadTape
-    $MTX -f $TAPELIBRARY load $SLOT $TAPEDRIVE
+    $MTX -f $TAPELIBRARY unload $storageSlot $DRIVE
 }
 
 function tapeRewind {
     echo "Rewinding Tape..."
-    $MT -f $TAPE rewind
+    timeout $TAPEREWIND_TIMEOUT $MT -f $TAPE rewind
 }
 
 function eraseTape {
     tapeRewind
     echo "Erasing Tape..."
     $MT -f $TAPE erase 0
+}
+
+function loadTape {
+    unloadTape
+    $MTX -f $TAPELIBRARY load $SLOT $DRIVE || return $?
 }
 
 function sizeRemain {
@@ -91,13 +98,13 @@ function find_select {
 }
 
 function tar_cmd {
-    # tar --format=pax -T - -I"zstd -19 -T0" -cf - 2>/dev/null
     tar --format=pax -T - -cf - 2>/dev/null
 }
 
 function mbuffer_send {
     local mbuffer_args=("--pid")
-    [[ $NSLOTS -gt $SLOT ]] && local mbuffer_args+=("-A $MTX -f $TAPELIBRARY next $TAPEDRIVE")
+    [[ -z $VERBOSE ]] && mbuffer_args+=("-q")
+    [[ $NSLOTS -gt $SLOT ]] && local mbuffer_args+=("-A $MTX -f $TAPELIBRARY next $DRIVE")
     mbuffer -s $((BS * 512)) -m 10% -o $TAPE "${mbuffer_args[@]}" 2>/dev/null
 }
 
@@ -164,11 +171,11 @@ function main {
 
     [[ -z $SLOT ]] && usage
 
-    echo "Directory: $DIR"
-    echo "Tape dev: $TAPE"
-    echo "Blocksize: $((BS * 512 / 1024))kb"
-    echo "Tape Library dev: $TAPELIBRARY"
-    echo "TapeLibrary Storage: $SLOT..$NSLOTS"
+    if [[ -n $VERBOSE ]]; then
+        echo "Directory: $DIR"
+        echo "Blocksize: $((BS * 512 / 1024))kb"
+        echo "TapeLibrary Storage: $SLOT..$NSLOTS"
+    fi
 
     if [[ -z $FULL && $(sizeFiles) -lt 1048576 ]]; then
         echo "Nothing new to backup"
@@ -186,7 +193,7 @@ function main {
         showFilesSize
         showRemainSize
         while [[ "$(($(sizeFiles) / 1048576))" -gt "$(sizeRemain)" ]]; do
-            $MTX -f $TAPELIBRARY next $TAPEDRIVE
+            $MTX -f $TAPELIBRARY next $DRIVE
             showRemainSize
             if [[ $SLOT -eq $NSLOTS ]]; then
                 echo "Last Tape full"
diff --git a/bin/.bin/server/zfs2tape b/bin/.bin/server/zfs2tape
--- a/bin/.bin/server/zfs2tape
+++ b/bin/.bin/server/zfs2tape
@@ -2,54 +2,56 @@
 MTX="/usr/local/bin/mtx"
 MT="/usr/bin/mt"
 SG="/usr/bin/sg_read_attr"
-LSSCSI="/usr/bin/lsscsi"
-DRIVE="J451"
-TAPE=$($LSSCSI | grep $DRIVE | awk '{print $6}')
-TAPE=$(echo "/dev/nst${TAPE: -1:1}")
-BS=512
-TAPELIBRARY=$($LSSCSI -g | grep mediumx | awk '{print $7}')
-TAPEDRIVE=${TAPE: -1:1}
-FILES_ONTAPE=0
+RE='^[0-9]+$'
+DRIVE=${DRIVE:-0}
+[[ $DRIVE =~ $RE ]] || exit 1
+if [[ "$DRIVE" -eq 0 ]]; then
+    TAPE=/dev/tape/by-path/pci-0000:0b:00.1-fc-0x2002000e11150604-lun-0-nst
+elif [[ "$DRIVE" -eq 1 ]]; then
+    TAPE=/dev/tape/by-path/pci-0000:85:00.0-sas-phy3-lun-0-nst
+else
+    echo "Drive not found"
+    exit 1
+fi
 TAPEREWIND_TIMEOUT=300
 TAPEREADY_TIMEOUT=3
+TAPELIBRARY=/dev/tape/by-path/pci-0000:0b:00.1-fc-0x2002000e11150604-lun-1-changer
+BS=${BS:-512}
+[[ $BS =~ $RE ]] || exit 1
+FILES_ONTAPE=0
 
 function usage {
     echo "usage: $(basename $0) [options] dataset init_slot [n_slots] [prefix]"
     echo "options:"
-    echo "[-b '$BS']"
     echo "[-f] Full Backup"
     echo "[-r] Don't create new snapshot, only backup existing ones"
-    echo "[-t '$TAPE'] "
     echo "[-v] Verbose"
     exit 1
 }
 
-while getopts "b:frt:v" o; do
+while getopts "frv" o; do
     case "$o" in
-    b) BS="$OPTARG" ;;
     f) FULL=TRUE ;;
     r) RECURSIVE_ONLY=true ;;
-    t)
-        TAPE="$OPTARG"
-        TAPEDRIVE=${TAPE: -1:1}
-        ;;
-    v) QUIET=TRUE ;;
+    v) VERBOSE=TRUE ;;
     *) usage ;;
     esac
 done
 shift $((OPTIND - 1))
 
+function tapeRewind {
+    echo "Rewinding tape!"
+    timeout $TAPEREWIND_TIMEOUT $MT -f $TAPE rewind
+}
+
 function eraseTape {
     echo "Erasing Tape.."
-    timeout $TAPEREWIND_TIMEOUT $MT -f $TAPE erase 0
+    tapeRewind
+    $MT -f $TAPE erase 0 # fast erase
 }
 
 function findEOM {
-    if [[ -n $FULL ]]; then
-        FILES_ONTAPE=0
-        eraseTape
-        return 0
-    fi
+    [[ -n $FULL ]] && eraseTape
     echo "Finding EOM..."
     local count=3
     while true; do
@@ -81,37 +83,32 @@ function tapeSerial {
 }
 
 function tapeBarcode {
-    local driveStatus=$($MTX -f $TAPELIBRARY status | grep "Data Transfer Element ${TAPEDRIVE}:")
+    local driveStatus=$($MTX -f $TAPELIBRARY status | grep "Data Transfer Element ${DRIVE}:")
     local barcode=$(echo $driveStatus | awk '{print $10}')
     echo "Tape barcode: $barcode"
 }
 
 function unloadTape {
-    local driveStatus=$($MTX -f ${TAPELIBRARY} status | grep "Data Transfer Element ${TAPEDRIVE}:")
+    local driveStatus=$($MTX -f $TAPELIBRARY status | grep "Data Transfer Element ${DRIVE}:")
     local driveLoaded=$(echo $driveStatus | awk -F ':' '{print $2}')
     [[ ${driveLoaded} == "Empty" ]] && return 0
     local storageSlot=$(echo $driveStatus | awk '{print $7}')
-    $MTX -f $TAPELIBRARY unload $storageSlot $TAPEDRIVE
+    $MTX -f $TAPELIBRARY unload $storageSlot $DRIVE
 }
 
 function loadTape {
     unloadTape
-    $MTX -f $TAPELIBRARY load $1 $TAPEDRIVE || return $?
+    $MTX -f $TAPELIBRARY load $1 $DRIVE || return $?
     tapeBarcode
     tapeSerial
     findEOM
 }
 
 function loadNextTape {
-    $MTX -f $TAPELIBRARY next $TAPEDRIVE || return $?
+    $MTX -f $TAPELIBRARY next $DRIVE || return $?
     tapeBarcode
     tapeSerial
     findEOM
-}
-
-function tapeRewind {
-    echo "Rewinding tape!"
-    $MT -f $TAPE rewind
 }
 
 function checkSize {
@@ -120,8 +117,7 @@ function checkSize {
     local size_remain_mb=$(tapeStatus '-f 0x0' 2>/dev/null | awk '{print $6}' | bc) || return $?
     [[ $snap_size_mb -ge 10000 ]] && echo "Snapshot size: $((snap_size_mb / 1024))GiB" || echo "Snapshot size: ${snap_size_mb}MiB"
     [[ $size_remain_mb -ge 10000 ]] && echo "Tape remain size: $((size_remain_mb / 1024))GiB" || echo "Tape remain size: ${size_remain_mb}MiB"
-
-    [[ "${size_remain_mb}" -ge "((snap_size_mb))" ]] && return $? || echo "Insuficient remain space on tape"
+    [[ "${size_remain_mb}" -ge "((snap_size_mb))" ]] && return 0 || echo "Insuficient remain space on tape"
     return 1
 }
 
@@ -137,8 +133,8 @@ function destroySnap {
 
 function send2tape {
     local mbuffer_args=("--pid")
-    [[ -z $QUIET ]] && mbuffer_args+=("-q")
-    [[ $NSLOTS -gt $SLOT ]] && mbuffer_args+=("-A $MTX -f $TAPELIBRARY next $TAPEDRIVE")
+    [[ -z $VERBOSE ]] && mbuffer_args+=("-q")
+    [[ $NSLOTS -gt $SLOT ]] && mbuffer_args+=("-A $MTX -f $TAPELIBRARY next $DRIVE")
     zfs send -wc $1 | mbuffer \
         -m 10% -s $((BS * 512)) "${mbuffer_args[@]}" -o $TAPE 2>/dev/null
 }
@@ -157,7 +153,7 @@ function firstSnapshot {
     echo "Sending first snapshot: $snap_init"
     checkSize "-R $snap_init"
     send2tape "-R $snap_init"
-    if [[ ! $? -eq 0 ]]; then
+    if [[ $? -ne 0 ]]; then
         [[ -n $created_now ]] && destroySnap $snap_init
         unloadTape
         return 1
@@ -235,19 +231,19 @@ function main {
     local ds=$1
     local prefix="${4:-tapebkp}"
 
-    [[ $SLOT =~ ^[0-9]+$ && $NSLOTS =~ ^[0-9]+$ ]] || usage
+    [[ $SLOT =~ $RE && $NSLOTS =~ $RE ]] || usage
     [[ -z $ds || -z $SLOT ]] && usage
     NSLOTS=$((SLOT + NSLOTS))
 
     zfs list -H -o name $ds >/dev/null || exit $?
 
-    echo "TapeLibrary: $TAPELIBRARY"
-    echo "Library Drive: $TAPEDRIVE"
-    echo "Tape Drive: $TAPE"
-    echo "Block Size: $((BS * 512 / 1024))k"
-    echo "Storage Slot: $SLOT .. $NSLOTS"
-    echo "Dataset: $ds"
-    echo "Prefix: $prefix"
+    if [[ -n $VERBOSE ]]; then
+        echo "Block Size: $((BS * 512 / 1024))k"
+        echo "Storage Slot: $SLOT .. $NSLOTS"
+        echo "Dataset: $ds"
+        echo "Prefix: $prefix"
+    fi
+
     echo "Begin of backup - $(date --utc +%Y/%m/%d-%H:%M)"
     [[ -n $RECURSIVE_ONLY ]] && echo "Recursive Snapshot Send Only, no new snapshot"
 
