removing extention from bash scripts and improving backup scripts

diff --git a/bin/.bin/server/snapsize b/bin/.bin/server/snapsize
--- a/bin/.bin/server/snapsize
+++ b/bin/.bin/server/snapsize
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 if [ -z $1 ]; then
-	echo "missing pool/dataset"
-	exit 1
+    echo "missing pool/dataset"
+    exit 1
 fi
 repo=$1
 filter=$2
@@ -9,19 +9,17 @@ filter=$2
 list=$(zfs list -t snapshot -H -o name ${repo})
 
 for i in ${list[@]}; do
-	[[ "$i" == *"${filter}"* ]] && arr+=($i)
+    [[ "$i" == *"${filter}"* ]] && arr+=($i)
 done
 
 firstsizes=$(zfs send -Pnwc ${arr[0]} | tail -1 | awk '{print $2}')
 firstsizes_mb=$(echo "${firstsizes} / 1024^2" | bc)
-firstsizes_gb=$(echo "scale=2;${firstsizes_mb} / 1024" | bc)
-echo "initial snapshot ${arr[0]}: ${firstsizes_mb}MiB / ${firstsizes_gb}GiB"
+echo "initial snapshot ${arr[0]}: ${firstsizes_mb}MiB"
 
 for ((i = 0; i < ${#arr[@]} - 1; i++)); do
-	sizes=$(zfs send -PnwcI ${arr[$i]} ${arr[(($i + 1))]} | tail -1 | awk '{print $2}')
-	sizes_mb=$(echo "${sizes} / 1024^2" | bc)
-	sizes_gb=$(echo "scale=2;${sizes_mb} / 1024" | bc)
-	echo "inc from ${arr[$i]} to ${arr[(($i + 1))]}: ${sizes_mb}MiB / ${sizes_gb}GiB"
+    sizes=$(zfs send -PnwcI ${arr[$i]} ${arr[(($i + 1))]} | tail -1 | awk '{print $2}')
+    sizes_mb=$(echo "${sizes} / 1024^2" | bc)
+    echo "inc from ${arr[$i]} to ${arr[(($i + 1))]}: ${sizes_mb}MiB"
 done
 
 lastsizes=$(zfs send -PnwcR ${arr[-1]} 2>/dev/null | tail -1 | awk '{print $2}')
